apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-lb
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.name }}-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
