apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.reporting.name }}-credentials-secret"
  namespace: {{ .Values.namespace | quote }}
type: Opaque
data:
  credentialsFileContent: {{ .Values.credentialsFileContent | b64enc | quote }}

