apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.reporting.secretName | quote }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
data:
  SPREADSHEET_ID: {{ .Values.spreadsheetID | b64enc | quote }}
