services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telegram"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - network
    ports: 
      - 5432:5432
    env_file:
      - ./database/.env
  db:
    depends_on:
      postgres: 
        condition: service_healthy
        restart: true
    image: database
    container_name: db
    networks:
      - network
    ports: 
      - 8001:8001
    env_file:
        - ./database/.env
  image_processor:
    image: image_processor
    container_name: image_processor
    networks:
      - network
    ports: 
      - 8080:8080
    environment:
      PORT: 8080

networks:
    network:
      name: network
      driver: bridge
