services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telegram"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - network
    ports: 
      - 5432:5432
    env_file:
      - ./database/.env
    volumes:
          - type: bind
            source: ./postgres_data
            target: /var/lib/postgresql/data/
  db:
    depends_on:
      postgres: 
        condition: service_healthy
        restart: true
    image: database
    container_name: db
    networks:
      - network
    ports: 
      - 8081:8081
    env_file:
        - ./database/.env
  image_processor:
    image: image_processor
    container_name: image_processor
    networks:
      - network
    ports: 
      - 8083:8083
    environment:
      PORT: 8083
  payment:
    image: payment
    container_name: payment
    networks:
      - network
    ports: 
      - 8082:8082
    environment:
      PORT: 8082
  tg_bot:
    image: tg_bot
    container_name: tg_bot
    networks:
      - network
    ports:
      - 8080:8080
    env_file:
      - ./bot/.env
  reporting:
    image: reporting
    container_name: reporting
    networks:
      - network
    ports: 
      - 8084:8084
    env_file:
      ./reporting/.env


networks:
    network:
      name: network
      driver: bridge
