services:
  database:
    build:
      context: ./database
    image: yakiza/database:latest
  image_processor:
    build:
      context: ./image_processor
    image: yakiza/image_processor:latest
  payment:
    build:
      context: ./payment
    image: yakiza/payment:latest
  tg_bot:
    build:
      context: ./bot
    image: yakiza/tg_bot:latest
  reporting:
    build:
      context: ./reporting
    image: yakiza/reporting:latest
