#SPDX-License-Identifier: MIT-0
---
# tasks file for helm
- name: Install helm secrets
  become: no
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/jkroepke/helm-secrets
    plugin_version: 4.6.2

- name: Check if helmfile is Installed
  become: no
  ansible.builtin.command: helmfile version
  register: helmfile_install_status
  changed_when: false
  ignore_errors: yes

- name: Install helmfile
  when: helmfile_install_status.rc != 0
  include_role:
    name: darkwizard242.helmfile

- name: Run helmfile init
  become: no
  ansible.builtin.expect:
    command: helmfile init
    responses:
      '.*install.*': 'y'
  timeout: 0
  register: helmfile_status
  changed_when: 'helmfile_status.stdout != "helmfile initialization completed!"'
