apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.postgres.name }}-secret"
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | b64enc | quote }}
