apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
  namespace: {{ .Values.namespace | quote }}
spec:
  selector:
    app: "{{ .Values.name }}-app"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
