---
- name: Configure system
  hosts: linuxes
  become: yes
  vars:
    user: "{{ ansible_user }}"
    cpu_architecture: "arm64"

    neovim_version: "0.10.2"
    configuration_repo: "https://github.com/ProbablyDead/Lazy_nvim.git"

    helm_architecture: "{{ cpu_architecture }}"
    helm_version: "3.17.0"

    k9s_checksum: "sha256:b890a7a212a3fc69e6ea4b2a29d59f80ed501a27ad654c819a155cc7c3c6aa8d"
    k9s_version: "v0.32.7"
    k9s_user: "{{ user }}"
  roles:
    - "./roles/base"
    - "./roles/nvim-editor"
    - "./roles/docker"
    - "./roles/kubectl"
    - "./roles/minikube"
    - "./roles/helm"
    - "./roles/k9s"
