#SPDX-License-Identifier: MIT-0
---
# tasks file for learning-k8s
- name: Install docker
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups:
      - "docker"
    append: true
    
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg
    state: present

- name: Download the public signing key
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key"
    keyring: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"

- name: Change mode for key
  ansible.builtin.file:
    path: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
    mode: "0644"

- name: Add repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    filename: "/etc/apt/sources.list.d/kubernetes.list"
    mode: "0644"
    state: present

- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present

- name: Download minikube
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm64"
    dest: "/home/{{ user }}/minikube"
    mode: "0774"

- name: Creates directory
  ansible.builtin.file:
    path: "/usr/local/bin/"
    state: "directory"

- name: Install minikube
  ansible.builtin.command: "install /home/{{ user }}/minikube /usr/local/bin/"

- name: Clean up
  ansible.builtin.file:
    path: "/home/{{ user }}/minikube"
    state: "absent"
