apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.payment.name }}-secret"
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  SHOP_ID: {{ .Values.shopID | b64enc | quote }}
  SHOP_KEY: {{ .Values.shopKey | b64enc | quote }}

