apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.databaseinterface.name }}-secret"
  namespace: {{ .Values.namespace | quote }}
type: Opaque
data:
  DB_USER: {{ .Values.postgresUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresPassword | b64enc | quote }}

