apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.payment.secretName | quote }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
data:
  SHOP_ID: {{ .Values.shopID | b64enc | quote }}
  SHOP_KEY: {{ .Values.shopKey | b64enc | quote }}

