#SPDX-License-Identifier: MIT-0
---
# tasks file for docker
- name: Install docker
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups:
      - "docker"
    append: true

- name: Install required dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: '0644'

- name: Get arch info
  ansible.builtin.shell: '. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"'
  register: os_data
  changed_when: false

- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ cpu_architecture }} signed-by=/etc/apt/keyrings/docker.asc]
       https://download.docker.com/linux/ubuntu
       {{ os_data.stdout }} stable
    filename: "/etc/apt/sources.list.d/docker"
    mode: "0644"
    state: present

- name: Install docker compose
  ansible.builtin.apt:
    update_cache: yes
    name: docker-compose-plugin
    state: present

- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta: reset_connection
