#SPDX-License-Identifier: MIT-0
---
# tasks file for docker
- name: Install docker
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups:
      - "docker"
    append: true

- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta: reset_connection
