namespace: &namespace "souvenir"
defaultPort: &defaultPort 80
defaultPullPolicy: &defaultPullPolicy "Always"

imageprocessor:
  name: image-processor
  image:
    repository: "yakiza/image_processor"
    tag: "latest"
  pullPoicy: *defaultPullPolicy
  namespace: *namespace
  port: *defaultPort
  replicasCount: 3

payment:
  name: payment
  image:
    repository: "yakiza/payment"
    tag: "latest"
    pullPoicy: *defaultPullPolicy
  namespace: *namespace
  port: *defaultPort
  replicasCount: 3
  isSecrets: true

reporting:
  name: reporting
  image:
    repository: "yakiza/reporting"
    tag: "latest"
    pullPoicy: *defaultPullPolicy
  namespace: *namespace
  port: *defaultPort
  isSecrets: true
  isCredentials: true
  replicasCount: 3
  credentialsFilePath: "/var/souvenir/google_creds"
  credentialsFileName: "credentials.json"
  ingredient_question_count: "6"

postgres:
  name: postgres
  image:
    repository: "postgres"
    tag: "17.2-alpine"
    pullPoicy: "IfNotPresent"
  namespace: *namespace
  replicaCount: 1
  service:
    type: "ClusterIP"
    port: 5432
  persistence:
    accessMode: ReadWriteOnce
    size: 3Gi
  postgresDB: "telegram"

databaseinterface:
  name: database-interface
  image:
    repository: "yakiza/database"
    tag: "latest"
    pullPoicy: *defaultPullPolicy
  namespace: *namespace
  port: *defaultPort
  isSecret: true
  replicaCount: 1
  waitFor:
    services:
      - "postgres-service"
      - "reporting-lb"
  db:
    host: "postgres-service"
    port: 5432
    name: "telegram"
    ssl: "disable"
  port: *defaultPort
  reporting:
    host: "reporting-lb"
    port: *defaultPort
