apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.reporting.name }}-secret"
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  SPREADSHEET_ID: {{ .Values.spreadsheetID | b64enc | quote }}
